-- Q1. What is the total revenue generated?
SELECT SUM(revenue) AS total_revenue
FROM ecommerce_data;


-- Q2. Which state generates the highest revenue?
SELECT state, SUM(revenue) AS total_revenue
FROM ecommerce_data
GROUP BY state
ORDER BY total_revenue DESC
LIMIT 1;


-- Q3. Which category generates the highest revenue?
SELECT category, SUM(revenue) AS total_revenue
FROM ecommerce_data
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 1;


-- Q4. What is the average discount offered?
SELECT AVG(discount_percent) AS avg_discount
FROM ecommerce_data;


-- Q5. Which age group contributes the most revenue?
SELECT age_group, SUM(revenue) AS total_revenue
FROM ecommerce_data
GROUP BY age_group
ORDER BY total_revenue DESC
LIMIT 1;


-- Q6. What is the revenue generated by each customer gender?
SELECT customer_gender, SUM(revenue) AS total_revenue
FROM ecommerce_data
GROUP BY customer_gender;


-- Q7. What are the top 5 categories by units sold?
SELECT category, SUM(units_sold) AS total_units
FROM ecommerce_data
GROUP BY category
ORDER BY total_units DESC
LIMIT 5;


-- Q8. What is the revenue generated during each sales event?
SELECT sales_event, SUM(revenue) AS total_revenue
FROM ecommerce_data
GROUP BY sales_event
ORDER BY total_revenue DESC;


-- Q9. What is the total number of units sold for each discount percentage?
SELECT discount_percent, SUM(units_sold) AS total_units
FROM ecommerce_data
GROUP BY discount_percent
ORDER BY discount_percent DESC;


-- Q10. What is the monthly revenue trend?
SELECT DATE_FORMAT(order_date, '%Y-%m') AS month,
       SUM(revenue) AS total_revenue
FROM ecommerce_data
GROUP BY month
ORDER BY month;